### ISSUE TITLE
"vendor/ember-cli-bootstrap/shim.js" did not match any files

### ISSUE THREAD

**Issue by mikeumus** [linstula/ember-cli-bootstrap#35]
On a fresh ember-cli app, installing ember-cli-bootstrap via `npm install --save-dev ember-cli-bootstrap` and setting `'importBootstrapJS': true` in the Brocfile, `ember s --live-reloard=false` outputs the following: 

```
(precise)mikeumus@localhost:~/Downloads/Mikeumus/projects/Kissagram/Development/miss-master$ ember s --live-reload=false
version: 0.1.3
Could not find watchman, falling back to NodeWatcher for file system events
Serving on http://0.0.0.0:4200/
Path or pattern "vendor/ember-cli-bootstrap/shim.js" did not match any files
Error: Path or pattern "vendor/ember-cli-bootstrap/shim.js" did not match any files
    at Object.multiGlob (/home/mikeumus/Downloads/Mikeumus/projects/Kissagram/Development/miss-master/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
    at /home/mikeumus/Downloads/Mikeumus/projects/Kissagram/Development/miss-master/node_modules/ember-cli/node_modules/broccoli-concat/index.js:62:32
    at $$$internal$$tryCatch (/home/mikeumus/Downloads/Mikeumus/projects/Kissagram/Development/miss-master/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/home/mikeumus/Downloads/Mikeumus/projects/Kissagram/Development/miss-master/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at $$$internal$$publish (/home/mikeumus/Downloads/Mikeumus/projects/Kissagram/Development/miss-master/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:453:11)
    at $$rsvp$asap$$flush (/home/mikeumus/Downloads/Mikeumus/projects/Kissagram/Development/miss-master/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
    at process._tickCallback (node.js:442:13)
```
This time the code is open. You may view it here: https://github.com/mikeumus/selfie

:smiley:

**Comment by jakecraige** [comment]
This is happening because [this commit](https://github.com/dockyard/ember-cli-bootstrap/commit/81f5a839b6ed46102a89bdeec68e3bd5b69cd350) added an import to a shims file and that file was never included in this repo. Probably because `vendor` is [gitignored](https://github.com/dockyard/ember-cli-bootstrap/blob/c8880dcaf0e8e7e3c94c1dada9db7695e36658d7/.gitignore) o.O

ping @linstula can you correct that?

**Comment by linstula** [comment]
`vendor` is no longer ignored. Version 0.0.14 has been published with the fix. Sorry for the confusion!
